import React, { useState } from 'react';
import { 
  FileText, 
  Printer, 
  Copy, 
  Check, 
  Download, 
  Sparkles,
  ArrowRight,
  BookOpen
} from 'lucide-react';

export default function BusinessPlanGenerator({ result, onNavigateTab }) {
  const [copied, setCopied] = useState(false);

  if (!result || !result.business_plan) {
    return (
      <div className="text-center py-16 bg-slate-900/40 rounded-2xl border border-slate-800 p-8">
        <FileText className="w-12 h-12 text-slate-600 mx-auto mb-3" />
        <h3 className="text-lg font-bold text-white mb-1">No Business Plan Generated Yet</h3>
        <p className="text-sm text-slate-400 mb-4">Validate an idea first to automatically compile an investor-grade business plan.</p>
        <button
          onClick={() => onNavigateTab('validator')}
          className="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold"
        >
          Go to Idea Validator
        </button>
      </div>
    );
  }

  const { business_plan, startup_name, industry, country } = result;
  const { sections, generated_date, feasibility_summary } = business_plan;

  const handlePrint = () => {
    window.print();
  };

  const handleCopy = () => {
    const markdownContent = `# Business Plan: ${startup_name}
Sector: ${industry} | Region: ${country}
Generated by LaunchLens AI on ${generated_date}
Feasibility Score: ${feasibility_summary.score}/100 (${feasibility_summary.tier})

${sections.map(s => `## ${s.title}\n\n${s.content}`).join('\n\n---\n\n')}`;

    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="max-w-5xl mx-auto space-y-8">
      {/* Top Action Bar (Hidden during print) */}
      <div className="no-print bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-xl flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs uppercase tracking-wider font-bold text-indigo-400">
              Investor-Ready Deliverable
            </span>
            <span className="text-slate-600">•</span>
            <span className="text-xs text-slate-400">{sections.length} Chapters Generated</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-white">
            Structured Business Plan
          </h1>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={handleCopy}
            className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-xs font-semibold text-slate-200 border border-slate-700 transition-colors cursor-pointer"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400" />
                <span className="text-emerald-400">Copied to Clipboard!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy Markdown</span>
              </>
            )}
          </button>

          <button
            onClick={handlePrint}
            className="inline-flex items-center gap-1.5 px-5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-xs font-bold text-white shadow-md shadow-indigo-600/30 transition-all cursor-pointer"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print / Save as PDF</span>
          </button>
        </div>
      </div>

      {/* The Printable Business Plan Document Container */}
      <div className="print-container bg-slate-900/90 border border-slate-800 rounded-2xl p-8 sm:p-12 shadow-2xl space-y-10 text-slate-200">
        {/* Cover / Document Header */}
        <div className="border-b border-slate-800 pb-8 space-y-4 print-break-inside">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="w-3 h-3 rounded-full bg-indigo-500" />
              <span className="text-xs font-bold uppercase tracking-wider text-slate-400">
                LaunchLens AI Comprehensive Venture Report
              </span>
            </div>
            <span className="text-xs text-slate-400 font-mono">
              {generated_date}
            </span>
          </div>

          <h2 className="text-3xl sm:text-4xl font-extrabold text-white">
            {startup_name}
          </h2>
          <p className="text-sm text-slate-400">
            A comprehensive strategic and financial blueprint for market validation in the <strong className="text-slate-200">{industry}</strong> domain.
          </p>

          <div className="flex flex-wrap items-center gap-3 pt-2">
            <span className="text-xs px-3 py-1 rounded-full bg-indigo-500/10 text-indigo-300 border border-indigo-500/30 font-semibold">
              Feasibility Score: {feasibility_summary.score}/100
            </span>
            <span className="text-xs px-3 py-1 rounded-full bg-slate-800 text-slate-300 border border-slate-700">
              Sector: {industry}
            </span>
            <span className="text-xs px-3 py-1 rounded-full bg-slate-800 text-slate-300 border border-slate-700">
              Jurisdiction: {country}
            </span>
          </div>
        </div>

        {/* Chapters */}
        <div className="space-y-10">
          {sections.map((sec) => (
            <div key={sec.id} className="space-y-3.5 print-break-inside">
              <h3 className="text-xl font-bold text-white border-b border-slate-800/80 pb-2">
                {sec.title}
              </h3>
              <div className="text-sm text-slate-300 leading-relaxed whitespace-pre-line font-sans">
                {sec.content}
              </div>
            </div>
          ))}
        </div>

        {/* Attribution Footer */}
        <div className="pt-8 border-t border-slate-800 text-xs text-slate-500 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2">
          <div>
            <span>Department of Information Technology • A.Y. 2026–2027</span>
          </div>
          <div>
            <span>Generated via LaunchLens Machine Learning Engine</span>
          </div>
        </div>
      </div>
    </div>
  );
}
